imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: AppBundle\Entity\Utilisateur
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
# app/config/config.yml 
vich_uploader: 
    db_driver: orm 
    mappings: 
        photo: 
            uri_prefix: /photos
            upload_destination: '%kernel.root_dir%/../web/photos' 
            namer: vich_uploader.namer_uniqid
easy_admin:
    site_name: 'Carcassonne Immo<a href="/" class="btn btn-primary"><i class="fa fa-arrow-circle-left"></i> Retour sur le site</a>'
    list:
        actions:
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'remove' }
    design:
        brand_color: '#838181'

    entities:
        Utilisateur:
            class: AppBundle\Entity\Utilisateur
            form:
                fields:
                    -  {property: username, label: "Identifiant de connexion" }
                    -  {property: email,label: "Email" }
                    -  {property: nom, label: "Nom" }
                    -  {property: prenom , label: "Prénom"}
                    -  {property: telephone, label: "Numéro de téléphone" }                                
                    # - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_ADMIN': 'ROLE_ADMIN' } } }                
                    # - { property: 'avatarFile', type: 'vich_image' }
            new:   
                title: "Création d'un utilisateur"      
                fields:
                    -  {property: 'plainPassword', label: "Mot de passe",  type: 'password', type_options: { required: true }}
            edit:
                title: "Modification d'un utilisateur"
            list:
                title: "Liste des utilisateurs"            
                fields:
                    -  {property: nom, label: "Nom" }
                    -  {property: prenom , label: "Prénom"}
                    # - { property: 'avatar', type: 'image', base_path: '%app.path.user_avatars%' }
        Client:
            class: AppBundle\Entity\Client
            form:
                fields:
                    -  {property: nom, label: "Nom" }
                    -  {property: prenom , label: "Prénom"}
                    -  {property: telephone, label: "Numéro de téléphone" }  
            new:   
                title: "Création d'un client"      
            edit:
                title: "Modification d'un client"
            list:
                title: "Liste des clients"                        
                fields:
                    -  {property: nom, label: "Nom" }
                    -  {property: prenom , label: "Prénom"}
                    -  {property: telephone, label: "Numéro de téléphone" }  
        Categorie:
            class: AppBundle\Entity\Categorie
            form:
                fields:
                    -  {property: titre, label: "Catégorie" }
            new:   
                title: "Création d'une catégorie"      
            edit:
                title: "Modification d'une catégorie"
            list:
                title: "Liste des catégories"                        
                fields:
                    -  {property: titre, label: "Catégorie" }
        Annonce:
            class: AppBundle\Entity\Annonce
            form:         
                fields:
                    -  {property: client, label: "Client" }
                    -  {property: categorie, label: "Catégorie" }
                    -  {property: titre, label: "Titre de l'annonce" }
                    -  {property: prix, label: "Prix" }                    
                    -  {property: description,type: 'textarea', label: "Déscription" }
                    -  {property: nombrePiece, label: "Nombre de pièces" }
                    # - utilisateur
            new:                     
                title: "Création d'une annonce"   
                fields:
                    -  {property: 'photoFile', type: 'vich_image', type_options: { required: true } }               
            edit:
                title: "Modification d'une annonce"
                fields:
                    -  {property: 'photoFile', type: 'vich_image' }               
                
            list:
                title: "Liste des annonces"                        
                fields:
                    -  {property: 'photo', type: 'image', base_path: 'photos' } 
                    -  {property: titre, label: "Titre de l'annonce" }
                    -  {property: utilisateur, label: "Auteur" }
                    


